### ISSUE TITLE
Remove `did:key` support in favor of  `did:web`

### ISSUE THREAD

**Issue by brownoxford** [w3c-ccg/traceability-interop#389]
Per the discussion in #342, support for `did:key` will be removed in favor of requiring and using `did:web` exclusively. This issue will be considered done when the following items have been addressed:

- [x] Remove references to `alsoKnownAs` from OpenAPI schema (#390)
- [x] Remove references to `alsoKnownAs` from  [`discovery.md`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/discovery.md) and [`use-case-requirements.html`](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/spec/sections/use-case-requirements.html) (#403)
- [x] Remove use of `alsoKnownAs` from Postman interoperability test suite and documentation (#392)
- [x] Remove use of `alsoKnownAs` from Postman conformance test suite (#391)

Recommend creating separate PRs for these items where possible, and updating the item list with a PR number when available.

**Comment by brownoxford** [comment]
This can be closed, we did this.

**Comment by nissimsan** [comment]
We did this.
